### ISSUE TITLE
Issues with iOS

### ISSUE THREAD

**Issue by asacolips** [Handyfon/simplemobile#1]
iOS has the following two issues:

* Unable to uncollapse the sidebar after collapsing it.
* Token controls buttons are absent.

![foundry-ios](https://user-images.githubusercontent.com/8518810/82941749-837c7200-9f5c-11ea-9a67-afb56925bb14.png)

**Comment by Handyfon** [comment]
Seems like IOs prevents foundry fromme detecting the system. I will see what I can du but I fear that this is an issue with Core.

**Comment by Handyfon** [comment]
I fear that IOS will not be supported in the foreseeable future.
