### ISSUE TITLE
0.2.0 causes desktop UI to change for mobile purposes

### ISSUE THREAD

**Issue by apoapostolov** [Handyfon/simplemobile#12]
Tested in 0.7.9, in Electron (Foundry's own). Confirmed with Culprit.

Causes the following changes to happen on the desktop at load:
- minimize sidebar
- minimize macro bar
- the canvas is mispositioned away from its set camera point

**Comment by Handyfon** [comment]
That will be an easy fix, thanks for creating this issue.
