### ISSUE TITLE
Feature Request: Access to Character Sheet only

### ISSUE THREAD

**Issue by baileywick** [Handyfon/simplemobile#4]
Great work! I use your module to give my players access to their character sheets during the game through their mobile phones. It's mobile responsive, integrated rolls, and just very, very effective. Better than managing everything on Beyond20 and trying to make those systems work together.

For performance and simplicity, is there any way to get rid of everything else (tokens, map, chat, combat tracker, etc) and just give them their sheets? Or perhaps you can let the GM pick which elements we give them?

**Comment by Handyfon** [comment]
There currently is no way to not load certain aspects of foundry, I'm not sure this module will support that in the future but I'll do my best.
