### ISSUE TITLE
When I tick"Performance Optimization" in the module settings the background disappears

### ISSUE THREAD

**Issue by noxichor** [Handyfon/simplemobile#6]
![Screenshot_20200729-160547~2](https://user-images.githubusercontent.com/68972136/88853742-cc97af00-d1b5-11ea-917c-a3c64445c59a.png)

I've tried messing around with a couple other settings like maximum framerate and stuff like that, but it doesn't really help as much. I'm on android and google chrome if that helps tho. I'm sorry to bug you :/

**Comment by Handyfon** [comment]
Sorry, it will make it clearer that the "Performance optimization" disables the canvas to save resources.
This mode is made for viewing the Character-Sheets / Chat and nothing else.
